// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: baji_ui

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
lv_obj_t * ui_ScreenMain;
lv_obj_t * ui_PanelStatus;
lv_obj_t * ui_PanelStatusBat;
lv_obj_t * ui_ImageStatuaBat;
lv_obj_t * ui_LabelStatuaBat;
lv_obj_t * ui_PanelStatusBright;
lv_obj_t * ui_ImageStatusBright;
lv_obj_t * ui_LabelStatusBright;
lv_obj_t * ui_PanelStatusCpu;
lv_obj_t * ui_ImageStatusCpu;
lv_obj_t * ui_LabelStatusCpu;
lv_obj_t * ui_PanelStatusRam;
lv_obj_t * ui_ImageStatusRam;
lv_obj_t * ui_LabelStatusRam;
lv_obj_t * ui_PanelAppPixel;
lv_obj_t * ui_ImageAppPixel;
lv_obj_t * ui_LabelSettingPixel;
lv_obj_t * ui_PanelSetting;
lv_obj_t * ui_ImageSetting;
lv_obj_t * ui_LabelSetting;
lv_obj_t * ui_PanelAppBaji;
lv_obj_t * ui_ImageAppBaji;
lv_obj_t * ui_LabelSettingBaji;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenSettings
void ui_ScreenSettings_screen_init(void);
lv_obj_t * ui_ScreenSettings;
lv_obj_t * ui_PanelSetBrightness;
lv_obj_t * ui_ImageSetBrightness;
lv_obj_t * ui_BarSetBrightnessVal;
lv_obj_t * ui_LabelSetBrightnessVal;
lv_obj_t * ui_PanelSetBuzzer;
lv_obj_t * ui_ImageSetBuzzer;
lv_obj_t * ui_ImageSetBuzzerVal;
lv_obj_t * ui_PanelSetLedOnOff;
lv_obj_t * ui_ImageSetLedOnOff;
lv_obj_t * ui_ImageSetLedOnOffVal;
lv_obj_t * ui_PanelSetLedRgb;
lv_obj_t * ui_ImageSetLedRgb;
lv_obj_t * ui_BarSetLedRgbVal;
lv_obj_t * ui_LabelSetLedRgbVal;
lv_obj_t * ui_PanelGetTFStatus;
lv_obj_t * ui_ImageGetTFStatus;
lv_obj_t * ui_ImageGetTFStatusVal;
lv_obj_t * ui_PanelGetUsbStatus;
lv_obj_t * ui_ImageGetUsbStatus;
lv_obj_t * ui_ImageGetUSBStatusVal;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenTemplate
void ui_ScreenTemplate_screen_init(void);
lv_obj_t * ui_ScreenTemplate;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenMain_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenMain);
}
