// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: baji_ui

#ifndef _BAJI_UI_UI_H
#define _BAJI_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_PanelStatus;
extern lv_obj_t * ui_PanelStatusBat;
extern lv_obj_t * ui_ImageStatuaBat;
extern lv_obj_t * ui_LabelStatuaBat;
extern lv_obj_t * ui_PanelStatusBright;
extern lv_obj_t * ui_ImageStatusBright;
extern lv_obj_t * ui_LabelStatusBright;
extern lv_obj_t * ui_PanelStatusCpu;
extern lv_obj_t * ui_ImageStatusCpu;
extern lv_obj_t * ui_LabelStatusCpu;
extern lv_obj_t * ui_PanelStatusRam;
extern lv_obj_t * ui_ImageStatusRam;
extern lv_obj_t * ui_LabelStatusRam;
extern lv_obj_t * ui_PanelAppPixel;
extern lv_obj_t * ui_ImageAppPixel;
extern lv_obj_t * ui_LabelSettingPixel;
extern lv_obj_t * ui_PanelSetting;
extern lv_obj_t * ui_ImageSetting;
extern lv_obj_t * ui_LabelSetting;
extern lv_obj_t * ui_PanelAppBaji;
extern lv_obj_t * ui_ImageAppBaji;
extern lv_obj_t * ui_LabelSettingBaji;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenSettings
void ui_ScreenSettings_screen_init(void);
extern lv_obj_t * ui_ScreenSettings;
extern lv_obj_t * ui_PanelSetBrightness;
extern lv_obj_t * ui_ImageSetBrightness;
extern lv_obj_t * ui_BarSetBrightnessVal;
extern lv_obj_t * ui_LabelSetBrightnessVal;
extern lv_obj_t * ui_PanelSetBuzzer;
extern lv_obj_t * ui_ImageSetBuzzer;
extern lv_obj_t * ui_ImageSetBuzzerVal;
extern lv_obj_t * ui_PanelSetLedOnOff;
extern lv_obj_t * ui_ImageSetLedOnOff;
extern lv_obj_t * ui_ImageSetLedOnOffVal;
extern lv_obj_t * ui_PanelSetLedRgb;
extern lv_obj_t * ui_ImageSetLedRgb;
extern lv_obj_t * ui_BarSetLedRgbVal;
extern lv_obj_t * ui_LabelSetLedRgbVal;
extern lv_obj_t * ui_PanelGetTFStatus;
extern lv_obj_t * ui_ImageGetTFStatus;
extern lv_obj_t * ui_ImageGetTFStatusVal;
extern lv_obj_t * ui_PanelGetUsbStatus;
extern lv_obj_t * ui_ImageGetUsbStatus;
extern lv_obj_t * ui_ImageGetUSBStatusVal;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenTemplate
void ui_ScreenTemplate_screen_init(void);
extern lv_obj_t * ui_ScreenTemplate;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_battery_png);    // assets/battery.png
LV_IMG_DECLARE(ui_img_bright_png);    // assets/bright.png
LV_IMG_DECLARE(ui_img_cpu_png);    // assets/cpu.png
LV_IMG_DECLARE(ui_img_mem_png);    // assets/mem.png
LV_IMG_DECLARE(ui_img_pixel_png);    // assets/pixel.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_ane_png);    // assets/ane.png
LV_IMG_DECLARE(ui_img_brightset_png);    // assets/brightSet.png
LV_IMG_DECLARE(ui_img_beep_png);    // assets/beep.png
LV_IMG_DECLARE(ui_img_on_png);    // assets/on.png
LV_IMG_DECLARE(ui_img_led_png);    // assets/led.png
LV_IMG_DECLARE(ui_img_off_png);    // assets/off.png
LV_IMG_DECLARE(ui_img_rgb_png);    // assets/rgb.png
LV_IMG_DECLARE(ui_img_tf_png);    // assets/tf.png
LV_IMG_DECLARE(ui_img_disconnect_png);    // assets/disconnect.png
LV_IMG_DECLARE(ui_img_connect_png);    // assets/connect.png

// FONTS
LV_FONT_DECLARE(ui_font_FontMiSansNomal12);
LV_FONT_DECLARE(ui_font_FontMiSansNomal16);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
