// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: baji_ui

#include "../ui.h"

void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelSetBrightness = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelSetBrightness, 70);
    lv_obj_set_height(ui_PanelSetBrightness, 124);
    lv_obj_set_x(ui_PanelSetBrightness, 10);
    lv_obj_set_y(ui_PanelSetBrightness, 9);
    lv_obj_remove_flag(ui_PanelSetBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSetBrightness, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSetBrightness, lv_color_hex(0x1E2630), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSetBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSetBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSetBrightness = lv_image_create(ui_PanelSetBrightness);
    lv_image_set_src(ui_ImageSetBrightness, &ui_img_brightset_png);
    lv_obj_set_width(ui_ImageSetBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSetBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSetBrightness, 0);
    lv_obj_set_y(ui_ImageSetBrightness, -20);
    lv_obj_set_align(ui_ImageSetBrightness, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSetBrightness, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageSetBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarSetBrightnessVal = lv_bar_create(ui_PanelSetBrightness);
    lv_bar_set_value(ui_BarSetBrightnessVal, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarSetBrightnessVal, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarSetBrightnessVal, 58);
    lv_obj_set_height(ui_BarSetBrightnessVal, 9);
    lv_obj_set_x(ui_BarSetBrightnessVal, 0);
    lv_obj_set_y(ui_BarSetBrightnessVal, 48);
    lv_obj_set_align(ui_BarSetBrightnessVal, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BarSetBrightnessVal, lv_color_hex(0x96B3E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarSetBrightnessVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_BarSetBrightnessVal,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_BarSetBrightnessVal, lv_obj_get_style_pad_right(ui_BarSetBrightnessVal,
                                                                                  LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_LabelSetBrightnessVal = lv_label_create(ui_PanelSetBrightness);
    lv_obj_set_width(ui_LabelSetBrightnessVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSetBrightnessVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSetBrightnessVal, 0);
    lv_obj_set_y(ui_LabelSetBrightnessVal, 32);
    lv_obj_set_align(ui_LabelSetBrightnessVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetBrightnessVal, "50%");
    lv_obj_set_style_text_font(ui_LabelSetBrightnessVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSetBuzzer = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelSetBuzzer, 70);
    lv_obj_set_height(ui_PanelSetBuzzer, 124);
    lv_obj_set_x(ui_PanelSetBuzzer, 90);
    lv_obj_set_y(ui_PanelSetBuzzer, 9);
    lv_obj_remove_flag(ui_PanelSetBuzzer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSetBuzzer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSetBuzzer, lv_color_hex(0x1E2630), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSetBuzzer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSetBuzzer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSetBuzzer = lv_image_create(ui_PanelSetBuzzer);
    lv_image_set_src(ui_ImageSetBuzzer, &ui_img_beep_png);
    lv_obj_set_width(ui_ImageSetBuzzer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSetBuzzer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSetBuzzer, 0);
    lv_obj_set_y(ui_ImageSetBuzzer, -20);
    lv_obj_set_align(ui_ImageSetBuzzer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSetBuzzer, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageSetBuzzer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSetBuzzerVal = lv_image_create(ui_PanelSetBuzzer);
    lv_image_set_src(ui_ImageSetBuzzerVal, &ui_img_on_png);
    lv_obj_set_width(ui_ImageSetBuzzerVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSetBuzzerVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSetBuzzerVal, 0);
    lv_obj_set_y(ui_ImageSetBuzzerVal, 40);
    lv_obj_set_align(ui_ImageSetBuzzerVal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSetBuzzerVal, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageSetBuzzerVal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelSetLedOnOff = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelSetLedOnOff, 70);
    lv_obj_set_height(ui_PanelSetLedOnOff, 124);
    lv_obj_set_x(ui_PanelSetLedOnOff, 170);
    lv_obj_set_y(ui_PanelSetLedOnOff, 9);
    lv_obj_remove_flag(ui_PanelSetLedOnOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSetLedOnOff, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSetLedOnOff, lv_color_hex(0x1E2630), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSetLedOnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSetLedOnOff, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSetLedOnOff = lv_image_create(ui_PanelSetLedOnOff);
    lv_image_set_src(ui_ImageSetLedOnOff, &ui_img_led_png);
    lv_obj_set_width(ui_ImageSetLedOnOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSetLedOnOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSetLedOnOff, 0);
    lv_obj_set_y(ui_ImageSetLedOnOff, -20);
    lv_obj_set_align(ui_ImageSetLedOnOff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSetLedOnOff, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageSetLedOnOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageSetLedOnOffVal = lv_image_create(ui_PanelSetLedOnOff);
    lv_image_set_src(ui_ImageSetLedOnOffVal, &ui_img_off_png);
    lv_obj_set_width(ui_ImageSetLedOnOffVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSetLedOnOffVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSetLedOnOffVal, 0);
    lv_obj_set_y(ui_ImageSetLedOnOffVal, 40);
    lv_obj_set_align(ui_ImageSetLedOnOffVal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSetLedOnOffVal, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageSetLedOnOffVal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelSetLedRgb = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelSetLedRgb, 70);
    lv_obj_set_height(ui_PanelSetLedRgb, 124);
    lv_obj_set_x(ui_PanelSetLedRgb, 250);
    lv_obj_set_y(ui_PanelSetLedRgb, 9);
    lv_obj_remove_flag(ui_PanelSetLedRgb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSetLedRgb, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSetLedRgb, lv_color_hex(0x1E2630), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSetLedRgb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSetLedRgb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSetLedRgb = lv_image_create(ui_PanelSetLedRgb);
    lv_image_set_src(ui_ImageSetLedRgb, &ui_img_rgb_png);
    lv_obj_set_width(ui_ImageSetLedRgb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSetLedRgb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSetLedRgb, 0);
    lv_obj_set_y(ui_ImageSetLedRgb, -20);
    lv_obj_set_align(ui_ImageSetLedRgb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSetLedRgb, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageSetLedRgb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarSetLedRgbVal = lv_bar_create(ui_PanelSetLedRgb);
    lv_bar_set_value(ui_BarSetLedRgbVal, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarSetLedRgbVal, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarSetLedRgbVal, 58);
    lv_obj_set_height(ui_BarSetLedRgbVal, 9);
    lv_obj_set_x(ui_BarSetLedRgbVal, 0);
    lv_obj_set_y(ui_BarSetLedRgbVal, 48);
    lv_obj_set_align(ui_BarSetLedRgbVal, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BarSetLedRgbVal, lv_color_hex(0x96B3E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarSetLedRgbVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_BarSetLedRgbVal, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_BarSetLedRgbVal,
                                                                                                      lv_obj_get_style_pad_right(ui_BarSetLedRgbVal, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_LabelSetLedRgbVal = lv_label_create(ui_PanelSetLedRgb);
    lv_obj_set_width(ui_LabelSetLedRgbVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSetLedRgbVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSetLedRgbVal, 0);
    lv_obj_set_y(ui_LabelSetLedRgbVal, 32);
    lv_obj_set_align(ui_LabelSetLedRgbVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetLedRgbVal, "50%");
    lv_obj_set_style_text_font(ui_LabelSetLedRgbVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelGetTFStatus = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelGetTFStatus, 70);
    lv_obj_set_height(ui_PanelGetTFStatus, 124);
    lv_obj_set_x(ui_PanelGetTFStatus, 330);
    lv_obj_set_y(ui_PanelGetTFStatus, 9);
    lv_obj_remove_flag(ui_PanelGetTFStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelGetTFStatus, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelGetTFStatus, lv_color_hex(0x1E2630), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelGetTFStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelGetTFStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageGetTFStatus = lv_image_create(ui_PanelGetTFStatus);
    lv_image_set_src(ui_ImageGetTFStatus, &ui_img_tf_png);
    lv_obj_set_width(ui_ImageGetTFStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGetTFStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGetTFStatus, 0);
    lv_obj_set_y(ui_ImageGetTFStatus, -20);
    lv_obj_set_align(ui_ImageGetTFStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageGetTFStatus, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageGetTFStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageGetTFStatusVal = lv_image_create(ui_PanelGetTFStatus);
    lv_image_set_src(ui_ImageGetTFStatusVal, &ui_img_disconnect_png);
    lv_obj_set_width(ui_ImageGetTFStatusVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGetTFStatusVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGetTFStatusVal, 0);
    lv_obj_set_y(ui_ImageGetTFStatusVal, 40);
    lv_obj_set_align(ui_ImageGetTFStatusVal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageGetTFStatusVal, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageGetTFStatusVal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelGetUsbStatus = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelGetUsbStatus, 70);
    lv_obj_set_height(ui_PanelGetUsbStatus, 124);
    lv_obj_set_x(ui_PanelGetUsbStatus, 420);
    lv_obj_set_y(ui_PanelGetUsbStatus, 9);
    lv_obj_remove_flag(ui_PanelGetUsbStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelGetUsbStatus, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelGetUsbStatus, lv_color_hex(0x1E2630), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelGetUsbStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelGetUsbStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageGetUsbStatus = lv_image_create(ui_PanelGetUsbStatus);
    lv_image_set_src(ui_ImageGetUsbStatus, &ui_img_tf_png);
    lv_obj_set_width(ui_ImageGetUsbStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGetUsbStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGetUsbStatus, 0);
    lv_obj_set_y(ui_ImageGetUsbStatus, -20);
    lv_obj_set_align(ui_ImageGetUsbStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageGetUsbStatus, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageGetUsbStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageGetUSBStatusVal = lv_image_create(ui_PanelGetUsbStatus);
    lv_image_set_src(ui_ImageGetUSBStatusVal, &ui_img_connect_png);
    lv_obj_set_width(ui_ImageGetUSBStatusVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageGetUSBStatusVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageGetUSBStatusVal, 0);
    lv_obj_set_y(ui_ImageGetUSBStatusVal, 40);
    lv_obj_set_align(ui_ImageGetUSBStatusVal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageGetUSBStatusVal, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageGetUSBStatusVal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
