// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: baji_ui

#include "../ui.h"

static void ui_event_PanelSetting(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenSettings_screen_init);
        _ui_screen_delete(&ui_ScreenMain);
    }
}

static void ui_ScreenMain_create_group(void)
{
    lv_group_remove_all_objs(lv_group_get_default());
    lv_group_add_obj(lv_group_get_default(), ui_PanelAppPixel);
    lv_group_add_obj(lv_group_get_default(), ui_PanelAppBaji);
    lv_group_add_obj(lv_group_get_default(), ui_PanelSetting);
}

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelStatus = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_PanelStatus, 84);
    lv_obj_set_height(ui_PanelStatus, 124);
    lv_obj_set_x(ui_PanelStatus, 11);
    lv_obj_set_y(ui_PanelStatus, 9);
    lv_obj_remove_flag(ui_PanelStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelStatus, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelStatusBat = lv_obj_create(ui_PanelStatus);
    lv_obj_set_width(ui_PanelStatusBat, 38);
    lv_obj_set_height(ui_PanelStatusBat, 58);
    lv_obj_set_x(ui_PanelStatusBat, -13);
    lv_obj_set_y(ui_PanelStatusBat, -13);
    lv_obj_remove_flag(ui_PanelStatusBat,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_PanelStatusBat, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelStatusBat, lv_color_hex(0x44515F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelStatusBat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelStatusBat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageStatuaBat = lv_image_create(ui_PanelStatusBat);
    lv_image_set_src(ui_ImageStatuaBat, &ui_img_battery_png);
    lv_obj_set_width(ui_ImageStatuaBat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageStatuaBat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageStatuaBat, 0);
    lv_obj_set_y(ui_ImageStatuaBat, -8);
    lv_obj_set_align(ui_ImageStatuaBat, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ImageStatuaBat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelStatuaBat = lv_label_create(ui_PanelStatusBat);
    lv_obj_set_width(ui_LabelStatuaBat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStatuaBat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStatuaBat, 0);
    lv_obj_set_y(ui_LabelStatuaBat, 12);
    lv_obj_set_align(ui_LabelStatuaBat, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelStatuaBat, "80%");
    lv_obj_set_style_text_font(ui_LabelStatuaBat, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelStatusBright = lv_obj_create(ui_PanelStatus);
    lv_obj_set_width(ui_PanelStatusBright, 38);
    lv_obj_set_height(ui_PanelStatusBright, 58);
    lv_obj_set_x(ui_PanelStatusBright, 27);
    lv_obj_set_y(ui_PanelStatusBright, -13);
    lv_obj_remove_flag(ui_PanelStatusBright,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_PanelStatusBright, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelStatusBright, lv_color_hex(0x44515F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelStatusBright, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelStatusBright, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageStatusBright = lv_image_create(ui_PanelStatusBright);
    lv_image_set_src(ui_ImageStatusBright, &ui_img_bright_png);
    lv_obj_set_width(ui_ImageStatusBright, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageStatusBright, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageStatusBright, 0);
    lv_obj_set_y(ui_ImageStatusBright, -10);
    lv_obj_set_align(ui_ImageStatusBright, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ImageStatusBright, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelStatusBright = lv_label_create(ui_PanelStatusBright);
    lv_obj_set_width(ui_LabelStatusBright, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStatusBright, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStatusBright, 0);
    lv_obj_set_y(ui_LabelStatusBright, 12);
    lv_obj_set_align(ui_LabelStatusBright, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelStatusBright, "100%");
    lv_obj_set_style_text_font(ui_LabelStatusBright, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelStatusCpu = lv_obj_create(ui_PanelStatus);
    lv_obj_set_width(ui_PanelStatusCpu, 38);
    lv_obj_set_height(ui_PanelStatusCpu, 58);
    lv_obj_set_x(ui_PanelStatusCpu, -13);
    lv_obj_set_y(ui_PanelStatusCpu, 47);
    lv_obj_remove_flag(ui_PanelStatusCpu,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_PanelStatusCpu, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelStatusCpu, lv_color_hex(0x44515F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelStatusCpu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelStatusCpu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageStatusCpu = lv_image_create(ui_PanelStatusCpu);
    lv_image_set_src(ui_ImageStatusCpu, &ui_img_cpu_png);
    lv_obj_set_width(ui_ImageStatusCpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageStatusCpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageStatusCpu, 0);
    lv_obj_set_y(ui_ImageStatusCpu, -10);
    lv_obj_set_align(ui_ImageStatusCpu, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ImageStatusCpu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelStatusCpu = lv_label_create(ui_PanelStatusCpu);
    lv_obj_set_width(ui_LabelStatusCpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStatusCpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStatusCpu, 0);
    lv_obj_set_y(ui_LabelStatusCpu, 12);
    lv_obj_set_align(ui_LabelStatusCpu, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelStatusCpu, "55%");
    lv_obj_set_style_text_font(ui_LabelStatusCpu, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelStatusRam = lv_obj_create(ui_PanelStatus);
    lv_obj_set_width(ui_PanelStatusRam, 38);
    lv_obj_set_height(ui_PanelStatusRam, 58);
    lv_obj_set_x(ui_PanelStatusRam, 27);
    lv_obj_set_y(ui_PanelStatusRam, 47);
    lv_obj_remove_flag(ui_PanelStatusRam,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_PanelStatusRam, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelStatusRam, lv_color_hex(0x44515F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelStatusRam, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelStatusRam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageStatusRam = lv_image_create(ui_PanelStatusRam);
    lv_image_set_src(ui_ImageStatusRam, &ui_img_mem_png);
    lv_obj_set_width(ui_ImageStatusRam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageStatusRam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageStatusRam, 0);
    lv_obj_set_y(ui_ImageStatusRam, -8);
    lv_obj_set_align(ui_ImageStatusRam, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ImageStatusRam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelStatusRam = lv_label_create(ui_PanelStatusRam);
    lv_obj_set_width(ui_LabelStatusRam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStatusRam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStatusRam, 0);
    lv_obj_set_y(ui_LabelStatusRam, 12);
    lv_obj_set_align(ui_LabelStatusRam, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelStatusRam, "30%");
    lv_obj_set_style_text_font(ui_LabelStatusRam, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAppPixel = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_PanelAppPixel, 70);
    lv_obj_set_height(ui_PanelAppPixel, 124);
    lv_obj_set_x(ui_PanelAppPixel, 105);
    lv_obj_set_y(ui_PanelAppPixel, 9);
    lv_obj_remove_flag(ui_PanelAppPixel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelAppPixel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelAppPixel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelAppPixel, lv_color_hex(0x44515F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_PanelAppPixel, lv_color_hex(0x5C5960), LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImageAppPixel = lv_image_create(ui_PanelAppPixel);
    lv_image_set_src(ui_ImageAppPixel, &ui_img_pixel_png);
    lv_obj_set_width(ui_ImageAppPixel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAppPixel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAppPixel, 0);
    lv_obj_set_y(ui_ImageAppPixel, -15);
    lv_obj_set_align(ui_ImageAppPixel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ImageAppPixel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSettingPixel = lv_label_create(ui_PanelAppPixel);
    lv_obj_set_width(ui_LabelSettingPixel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSettingPixel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSettingPixel, 0);
    lv_obj_set_y(ui_LabelSettingPixel, 5);
    lv_obj_set_align(ui_LabelSettingPixel, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelSettingPixel, "Pixel");
    lv_obj_set_style_text_font(ui_LabelSettingPixel, &ui_font_FontMiSansNomal16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSetting = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_PanelSetting, 70);
    lv_obj_set_height(ui_PanelSetting, 124);
    lv_obj_set_x(ui_PanelSetting, 265);
    lv_obj_set_y(ui_PanelSetting, 9);
    lv_obj_remove_flag(ui_PanelSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSetting, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSetting, lv_color_hex(0x44515F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_PanelSetting, lv_color_hex(0x5C5960), LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImageSetting = lv_image_create(ui_PanelSetting);
    lv_image_set_src(ui_ImageSetting, &ui_img_setting_png);
    lv_obj_set_width(ui_ImageSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSetting, 0);
    lv_obj_set_y(ui_ImageSetting, -15);
    lv_obj_set_align(ui_ImageSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSetting, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSetting = lv_label_create(ui_PanelSetting);
    lv_obj_set_width(ui_LabelSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSetting, 0);
    lv_obj_set_y(ui_LabelSetting, 5);
    lv_obj_set_align(ui_LabelSetting, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelSetting, "设置");
    lv_obj_set_style_text_font(ui_LabelSetting, &ui_font_FontMiSansNomal16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAppBaji = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_PanelAppBaji, 70);
    lv_obj_set_height(ui_PanelAppBaji, 124);
    lv_obj_set_x(ui_PanelAppBaji, 185);
    lv_obj_set_y(ui_PanelAppBaji, 9);
    lv_obj_remove_flag(ui_PanelAppBaji, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelAppBaji, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelAppBaji, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelAppBaji, lv_color_hex(0x44515F), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_PanelAppBaji, lv_color_hex(0x5C5960), LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImageAppBaji = lv_image_create(ui_PanelAppBaji);
    lv_image_set_src(ui_ImageAppBaji, &ui_img_ane_png);
    lv_obj_set_width(ui_ImageAppBaji, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAppBaji, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAppBaji, 0);
    lv_obj_set_y(ui_ImageAppBaji, -15);
    lv_obj_set_align(ui_ImageAppBaji, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ImageAppBaji, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSettingBaji = lv_label_create(ui_PanelAppBaji);
    lv_obj_set_width(ui_LabelSettingBaji, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSettingBaji, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSettingBaji, 0);
    lv_obj_set_y(ui_LabelSettingBaji, 5);
    lv_obj_set_align(ui_LabelSettingBaji, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelSettingBaji, "吧唧");
    lv_obj_set_style_text_font(ui_LabelSettingBaji, &ui_font_FontMiSansNomal16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PanelSetting, ui_event_PanelSetting, LV_EVENT_ALL, NULL);

    ui_ScreenMain_create_group();
}

void ui_enter_to_screenMain(void)
{
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenMain_screen_init);
}

void ui_exit_to_screenMain(void)
{
    _ui_screen_delete(&ui_ScreenMain);
}
