// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: baji_ui

#include "../ui.h"

void ui_ScreenTemplate_screen_init(void)
{
    ui_ScreenTemplate = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenTemplate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
